@echo off
title Cyber Sec Project Launcher
echo Starting Cyber Sec Project Application...

echo Starting Backend Server...
start "Backend Server" cmd /k "cd backend && python wsgi.py"

echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd frontend && npm run dev"

echo Both servers are starting...
echo Waiting a few seconds for the servers to initialize...
timeout /t 5 /nobreak >nul
echo Opening the application in your default web browser...
start http://localhost:5173
